name: develop auto pr
'on':
  push:
    branches:
      - develop

jobs:
  pull-request:
    name: Open PR to next
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: pull-request-next
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "next"
        pr_title: "Pulling ${{ github.ref }} into next"
        pr_body: "💥 *An automated PR*"
        pr_reviewer: "jl917"
        pr_draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: pull-request-master
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_body: "💥 *An automated PR*"
        pr_reviewer: "jl917"
        pr_draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: pull-request-main
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: "💥 *An automated PR*"
        pr_reviewer: "jl917"
        pr_draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
