# ./.github/workflows/staging-auto-pr.yaml
name: develop auto pr
on:
  push:
    branches: ['develop']

jobs:
  pull-request:
    name: Open PR to next
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "next"
        pr_title: "Pulling ${{ github.ref }} into next"
        pr_body: "💥 *An automated PR*"
        pr_reviewer: "jl917"
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "master"
        pr_title: "Pulling ${{ github.ref }} into next"
        pr_body: "💥 *An automated PR*"
        pr_reviewer: "jl917"
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}